---
- name: deployment
  hosts: apps
  become: true
  tasks:
    - name: deploy files
      copy: 
         src : var/lib/jenkins/workspace/buildanddeploy/target/hello-*.war
         dest : /var/lib/tomcat/webapps
          