---
- name: tom installation
  hosts: 
      - apps
  become: true
  tasks:
    - name: tom install
      yum:
          name: tomcat
          state: present
    - name: tomcat dependencies
      yum:
          name: "{{ item }}"
          state: present
      loop: 
             - tomcat-webapps 
             - tomcat-admin-webapps 
             - tomcat-docs-webapp
             - tomcat-javadoc    
    - name: restart tomcat
      service:
          name: tomcat
          state: restarted